In [1]:

import pandas as pd
import numpy as np
import math
import random
from datetime import datetime

In [28]:

import pandas as pd
import numpy as np
import math
import random
from datetime import datetime

df_card_port_cons = pd.DataFrame(columns=['per_num',
'vintage',
'product',
'prod_grp',
'prod_type',
'wallet_size',
'wallet_segment',
'cfo_revlv_ind',
'open_ind',
'spend_type',
'segment',
'ga_ind',
'graduated_ind',
'conv_ind',
'college_ind',
'accts_enr',
'accts_open',
'accts_active_bill',
'accts_active_sales',
'accts_bill_inactv_l12',
'accts_sales_inactive_l12',
'accts_new_acquired',
'accts_closed_new',
'accts_closed_vol',
'accts_closed_invol',
'accts_inactive_closed',
'accts_otherinvol_closed',
'accts_new_balcon',
'accts_enr_delq_26',
'accts_ncl',
'fico_score',
'fico_score_accts',
'accts_acctonlin_ever',
'accts_paperless_ever',
'accts_auth_primary_only',
'accts_auth_secondary',
'accts_auth_multiple',
'sales_purch',
'sales_offus',
'sales_new_balcon_ant',
'bal_anr',
'bal_enr',
'bal_bnr',
'bal_delnq_26',
'bal_full_rate_offus',
'bal_promo_offus',
'bal_rvlv_offus_bur',
'bal_rvlv_offus_argus',
'credt_limit_onus',
'pay_amt',
'pay_rate',
'bal_revolving',
'net_interest',
'cof',
'Interchange',
'fee_total',
'rebate',
'cnr',
'ebit',
'ncl',
'refill_points_rewplus',
'roundup_points_rewplus',
'points_back_10ptc_rewplus',
'Incap_2x_points_back_rewplus',
'metcap_1x_points_back_rewplus',
'acq_bonus_points',
'bonus_points',
'bal_bseg_intro_bt',
'bal_bseg_intro_spl',
'bal_bseg_intro_purch_promo',
'bal_bseg_intro_others',
'bal_bseg_goto',
'bal_bseg_risk',
'bal_bseg_flex_loan',
'bal_bseg_flex_pay',
'bal_bseg_amazon_pos',
'accts_bseg_flex_loan',
'accts_bseg_flex_pay',
'accts_bseg_amazon_pos',
'sales_bseg_flex_loan',
'sales_bseg_flex_pay',
'sales_bseg_amazon_pos',
'expedia_sales',
'travel_portal_sales',
'sb_capped_spend',
'spend1_airlines',
'txn_airlines',
'spend1_dining',
'txn_dining',
'spend1_entertainment',
'txn_entertainment',
'spend1_electronics',
'txn_electronics',
'spend1_home_Improvement',
'txn_house_improvement',
'spend1_grocery',
'txn_grocery',
'spend1_hotels_motels',
'txn_hotels_motels',
'spend_other_travel',
'spend_gas',
'txn_gas',
'txn_other_travel',
'spend_cruise',
'txn_cruise',
'spend1_total',
'txn_total',
'accts_airlines',
'accts_dining',
'accts_entertainment',
'accts_electronics',
'accts_home_improvement',
'accts_grocery',
'accts_hotels_motels',
'accts_other_travel',
'accts_gas',
'accts_cruise',
'accts_expedia',
'accts_travel_portal',
'accts_sb_capped_spend',
'refill_points_rewplus0',
'roundup_points_rewplus0',
'points_back_10ptc_resplus0',
'Incap_2x_points_back_rewplus0',
'metcap_1x_points_back_rewplus0',
'acq_bonus_points0',
'bonus_points0',
'spend_contactless',
'spend_online',
'spend_regular',
'txn_contactless',
'txn_online',
'txn_regular',
'accts_contactless',
'accts_online',
'accts_regular',
'acq_pre_preferred',
'acq_pre_premier',
'acq_pre_prestige',
'acq_pre_rplus',
'acq_pre_customcash',
'acq_pre_drivers_edge',
'acq_pre_simplicity',
'acq_pre_dp',
'acq_pre_oth_nonrewards',
'acq_pre_dc',
'acq_pre_dividend',
'acq_pre_oth_cash',
'acq_pre_aa',
'acq_pre_costco',
'acq_pre_oth_cobrands',
'acq_pre_others',
'ecm_pre_preferred',
'ecm_pre_premier',
'ecm_pre_prestige',
'ecm_pre_rplus',
'ecm_pre_customcash',
'ecm_pre_drivers_edge',
'ecm_pre_simplicity',
'ecm_pre_dp',
'ecm_pre_oth_nonrewards',
'ecm_pre_dc',
'ecm_pre_dividend',
'ecm_pre_oth_cash',
'ecm_pre_aa',
'ecm_pre_costco',
'ecm_pre_oth_cobrands',
'ecm_pre_others',
'points_earned_sp',
'points_earned_base_sp',
'points_redeemed_sp',
'point_balance',
'points_earned',
'earners',
'points_earned_base',
'base_earners',
'points_earned_bonus',
'bonus_earners',
'points_redeem',
'redeemers',
'points_redeemed_gc',
'gc_redeeners',
'points_redeemed_trvl',
'trvl_redeemers',
'points_redeemed_merch',
'merch_redeemers',
'points_redeemed_amazon',
'amazon_redeemers',
'accounts',
'members',
'yr',
'mon',
'monyr',
'monyyrchan'])

df_card_port_cons
num_rows=10000

def find_pernum(date):
    month=int(date[4:])
    year=int(date[:4])
    start_pernum, start_month, start_year=6405, 1, 2017
    year_diff = year - start_year
    pernum = start_pernum + 12 * year_diff + month - 1
    return pernum

all_yyyymm = [str(year) + str(month).zfill(2) for year in range(2017, 2023) for month in range(1, 13)]
all_yyyymm = [yyyymm for yyyymm in all_yyyymm if yyyymm <= '202309']
all_yyyymm = [yyyymm for yyyymm in all_yyyymm if yyyymm >= '201606']
ran_yyyymm = [random.choice(all_yyyymm) for _ in range(num_rows)]

df_card_port_cons ['per_num_yyyymm']= ran_yyyymm

df_card_port_cons ['per_num_yyyy']=df_card_port_cons ['per_num_yyyymm'].str[:4]
df_card_port_cons ['per_num_mm']=df_card_port_cons ['per_num_yyyymm'].str[4:]
df_card_port_cons ['per_num']=df_card_port_cons ['per_num_yyyymm'].apply(find_pernum)

df_card_port_cons['vintage'] = ['P' + yyyymm[:4] if int(yyyymm[:4]) <= 2017 else 'V' + yyyymm[:4] for yyyymm in ran_yyyymm]

product = ['AA Platinum', 'AA Executive', 'AA Gold', 'AA Mileup Bronze', 'ATT_Platinum',
           'ATT_Access More', 'ATT_Rewards', 'ATT_Access', 'Dividend', 'Double Cash', 
           'Costco Front Book', 'Costco Back Book', 'Expedia_Rewards', 'Expedia_Fee', 
           'Expedia_NoFee', 'Expedia_Rewards Voyager', 'Rewards+', 'Premier', 'Prestige', 
           'Preferred', 'Drivers Edge', 'Custom Cash', 'DP', 'Simplicity','Secured']
df_card_port_cons['product'] = np.random.choice(product,df_card_port_cons.shape[0],p=[0.08,0.012,0.016,0.016,0.007,0.005,0.011,0.001,0.001,
                                                                                      0.12,0.16,0.17,0.001,0.001,0.001,0.001,0.04,0.011,
                                                                                      0.001,0.11,0.004,0.035,0.112,0.08,0.004])

df_card_port_cons['prod_grp'] = df_card_port_cons['product'].map({
'AA Platinum':'AA',
'AA Executive':'AA',
'AA Gold':'AA',
'AA Mileup Bronze':'AA',
'ATT_Platinum':'ATT',
'ATT_Access More':'ATT',
'ATT_Rewards':'ATT',
'ATT_Access':'ATT',
'Dividend':'Cash',
'Double Cash':'Cash',
'Costco Front Book':'Costco',
'Costco Back Book':'Costco',
'Expedia_Rewards':'Expedia',
'Expedia_Fee':'Expedia',
'Expedia_NoFee':'Expedia',
'Expedia_Rewards Voyager':'Expedia',
'Rewards+':'TY',
'Premier':'TY',
'Prestige':'TY',
'Preferred':'TY',
'Drivers Edge':'TY',
'Custom Cash':'Cash',
'DP':'Value',
'Simplicity':'Value',
'Secured':'Value'
})


df_card_port_cons['prod_type'] = df_card_port_cons['product'].map({
'AA Platinum':'Cobrand',
'AA Executive':'Cobrand',
'AA Gold':'Cobrand',
'AA Mileup Bronze':'Cobrand',
'ATT_Platinum':'Cobrand',
'ATT_Access More':'Cobrand',
'ATT_Rewards':'Cobrand',
'ATT_Access':'Cobrand',
'Dividend':'PPM',
'Double Cash':'PPM',
'Costco Front Book':'Cobrand',
'Costco Back Book':'Cobrand',
'Expedia_Rewards':'Cobrand',
'Expedia_Fee':'Cobrand',
'Expedia_NoFee':'Cobrand',
'Expedia_Rewards Voyager':'Cobrand',
'Rewards+':'PPM',
'Premier':'PPM',
'Prestige':'PPM',
'Preferred':'PPM',
'Drivers Edge':'PPM',
'Custom Cash':'PPM',
'DP':'PPM',
'Simplicity':'PPM',
'Secured':'PPM'
})

wallet_size = ['HW', 'LW', 'MW', 'NULL', 'VHW']
wallet_segment_mapping = {
    'HW': 'HWR',
    'HW': 'HWT',
    'LW': 'LWR',
    'LW': 'LWT',
    'MW': 'MWR',
    'MW': 'MWT',
    'NULL': '',
    'VHW': 'HWT',
    'VHW': 'HWR'
}

df_card_port_cons['wallet_size'] = np.random.choice(wallet_size, df_card_port_cons.shape[0], p=[0.23, 0.21, 0.21, 0.14, 0.21])
df_card_port_cons['wallet_segment'] = df_card_port_cons['wallet_size'].map(wallet_segment_mapping)

df_card_port_cons

,per_num,vintage,product,prod_grp,prod_type,wallet_size,wallet_segment,cfo_revlv_ind,open_ind,spend_type,...,amazon_redeemers,accounts,members,yr,mon,monyr,monyyrchan,per_num_yyyymm,per_num_yyyy,per_num_mm
0,6452,V2020,Costco Back Book,Costco,Cobrand,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202012,2020,12
1,6470,V2022,Costco Back Book,Costco,Cobrand,NULL,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202206,2022,06
2,6460,V2021,Double Cash,Cash,PPM,LW,LWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202108,2021,08
3,6445,V2020,AA Platinum,AA,Cobrand,VHW,HWR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202005,2020,05
4,6469,V2022,Costco Front Book,Costco,Cobrand,NULL,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202205,2022,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,6471,V2022,Double Cash,Cash,PPM,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202207,2022,07
9996,6412,P2017,Rewards+,TY,PPM,HW,HWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201708,2017,08
9997,6445,V2020,AA Gold,AA,Cobrand,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202005,2020,05
9998,6416,P2017,Double Cash,Cash,PPM,LW,LWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201712,2017,12
9999,6432,V2019,Simplicity,Value,PPM,NULL,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201904,2019,04

In [3]:
table_name = 'card_port_cons_'
df_card_port_cons.columns = [table_name + str(i) for i in df_card_port_cons.columns]

df_info = pd.DataFrame(columns=['column_name', 'Data_type'])
df_info['column_name'] = df_card_port_cons.columns.tolist()
for i in range(df_info.shape[0]):
    df_info['Data_type'][i] = df_card_port_cons.iloc[:, i].dtype

df_card_port_cons.to_csv('df_card_port_cons.csv', index=False)
df_info.to_csv('df_card_port_cons_info.csv', index=False)

df_info

                   column_name Data_type
0       card_port_cons_per_num    object
1       card_port_cons_vintage    object
2       card_port_cons_product    object
3      card_port_cons_prod_grp    object
4     card_port_cons_prod_type    object
..                         ...       ...
189     card_port_cons_members    object
190          card_port_cons_yr    object
191         card_port_cons_mon    object
192       card_port_cons_monyr    object
193  card_port_cons_monyyrchan    object

[194 rows x 2 columns]